### PR TITLE
add validator voting smart contract

### PR DESCRIPTION
**Pull request by thanhson1085**
This PR aims to add validator voting smart contract that is used in governance dapp. the consensus need to read the smart contract to add/remove a validator.

- [x] validator proposes a new candidate
- [x] users vote for the candidates
- [x] get list of validators
- [x] blockSigners contract

### CODE REVIEW

**Comment by benjiqq** [comment]
Some notes going through the code (looks great):

-  propose to use constructor keyword
- at constructor check length and valid arrays, and possibly other values
- currently self-voting is allowed
- owner can't change the deposit amount (there could be a function changeDeposit which is based on updated balance)
- as I understand there will be a single instance of TomoValidator code at fixed address. maybe this could be notified somewhere (VALIDATOR_ADDRESS const)
- not clear to me yet how lock-in and reward will be plugged into the code

https://gist.github.com/benjyz/4556be5c835d6ce1fad89d06ad1b57c1

**Comment by thanhson1085** [comment]
The latest version of the smart contract we are developing at https://github.com/tomochain/tomochain-governance/blob/master/contracts/TomoValidator.sol. So if you have any patches, please pull request to that repository.

> propose to use constructor keyword

Yep, it for the new solidity compiler version

> at constructor check length and valid arrays, and possibly other values

We just deploy the contract in genesis block.

> currently self-voting is allowed

Yep, to against self-voting, you have KYC system.

> owner can't change the deposit amount (there could be a function changeDeposit which is based on updated balance)

Shout not, the coin will be locked after depositing or voting.

> as I understand there will be a single instance of TomoValidator code at fixed address. maybe this could be notified somewhere (VALIDATOR_ADDRESS const)

 Yep, it should be published in the specs.

> not clear to me yet how lock-in and reward will be plugged into the code

The reward engine will read smart contract and block header to know what validators will be rewarded.

**Comment by thanhson1085** [comment]
gen the go code:
```
~/go/src/github.com/ethereum/go-ethereum/build/bin/abigen --sol TomoValidator.sol --pkg contract --out validator.go
```

passed the test 
```
$ go test -v
=== RUN   TestValidator
--- PASS: TestValidator (0.02s)
        validator_test.go:35: candidate 0x71562b71999873DB5b286dF957af199Ec94617F7 cap 0
        validator_test.go:37: candidate 0x71562b71999873DB5b286dF957af199Ec94617F7 validator owner 0x71562b71999873DB5b286dF957af199Ec94617F7
PASS
ok      github.com/ethereum/go-ethereum/contracts/validator     0.061s
```

**Comment by benjiqq** [comment]
confirmed. took me a while since there is a name collision with validator.go which exists as 2 files in contracts/validator and contracts/validator/contract. 

```
$ cd ~/go/src/github.com/ethereum/go-ethereum/contracts/validator
$ git reset --hard
HEAD is now at 10f83d824 update latest validator contract
$ cat contract/TomoValidator.sol | openssl dgst -sha256 
189c37ce1d275c68e71df1fad134f15fced5ae6f90becddd39ac11eb54ca5d82
$ ~/go/src/github.com/ethereum/go-ethereum/build/bin/abigen --sol ./contract/TomoValidator.sol --pkg contract --out ./contract/validator.go
$ go test -v
=== RUN   TestValidator
--- PASS: TestValidator (0.01s)
	validator_test.go:35: candidate 0x71562b71999873DB5b286dF957af199Ec94617F7 cap 0
	validator_test.go:37: candidate 0x71562b71999873DB5b286dF957af199Ec94617F7 validator owner 0x71562b71999873DB5b286dF957af199Ec94617F7
PASS
ok  	github.com/ethereum/go-ethereum/contracts/validator	0.157s
```

**Comment by thanhson1085** [comment]
Added Block Signers contract
```
$ go test -v
=== RUN   TestBlockSigner
--- PASS: TestBlockSigner (0.01s)PASSok      github.com/ethereum/go-ethereum/contracts/blocksigner   0.046s
```

**Comment by thanhson1085** [comment]
@ngtuna should we merge this pull request. @dinhln89 need the contracts to implement the new consensus.

**Comment by thanhson1085** [comment]
I will create a new pull request for randomize smart contract later

**Comment by ngtuna** [comment]
there we go 🎉

**Pull request merged**
