### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by etienne-napoleone**
Add reference to masternode documentation and correct some typos

Note: the masternode documentation is not yet live. Might want to wait for it before merging or there will be a dead link

### CODE REVIEW

**Comment by ngtuna** [comment]
What's status of this PR @etienne-napoleone ?

**Comment by etienne-napoleone** [comment]
@ngtuna waiting for your review and merge

**Comment by etienne-napoleone** [comment]
@ngtuna I updated the readme after our talk

**Comment by ngtuna** [comment]
@etienne-napoleone cool thank you 👍 Looks nice now. Merging

**Pull request merged**
