### PR TITLE
add option genesis generator for POSV

### PR DESCRIPTION
**Pull request by thanhson1085**

### CODE REVIEW

**Comment by thanhson1085** [comment]
Some new things added in this PRs:
- new TomoValidator Smart Contract, voter withdraw delay
- generate genesis
- Randomize Smart contract

@ngtuna, @dinhln89  take a look

**Comment by ngtuna** [comment]
lgtm 👍 I will merge the PR if @dinhln89 is also fine with this

**Comment by dinhln89** [comment]
This PR working fine on my local chain. So i think it is ok for merge. lgtm! ^^!

**Comment by ngtuna** [comment]
cool. Merging now

**Pull request merged**
